version: "3.8"

services:
  fastapi_server:
    container_name: fastapi-your-data
    build: ./backend
    restart: always
    # Enable debug mode run .vscode/launch.json -> "Debug: Attach to FastAPI Docker"
    # command: "sh -c 'pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080 --loop asyncio'"
    # ports:
    #   - 5678:5678
    # Disable debug mode if only frontend development
    command: "sh -c 'uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8080
    env_file: ".env"
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: ankane/pgvector:v0.4.1
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/var/lib/postgresql
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
