name: fastapi-your-data
on:
  push:
    branches: [master]
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3 # Check if there's a newer version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # Check if there's a newer version

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4 # Check if there's a newer version

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # Check if there's a newer version
        with:
          context: ./backend
          dockerfile: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
